// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// crossprod_cpp
double crossprod_cpp(arma::vec v1, arma::vec v2);
RcppExport SEXP _MuFiMeshGP_crossprod_cpp(SEXP v1SEXP, SEXP v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v2(v2SEXP);
    rcpp_result_gen = Rcpp::wrap(crossprod_cpp(v1, v2));
    return rcpp_result_gen;
END_RCPP
}
// matMulVec_cpp
arma::vec matMulVec_cpp(arma::mat M, arma::vec v);
RcppExport SEXP _MuFiMeshGP_matMulVec_cpp(SEXP MSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(matMulVec_cpp(M, v));
    return rcpp_result_gen;
END_RCPP
}
// vecMulMat_cpp
arma::vec vecMulMat_cpp(arma::vec v, arma::mat M);
RcppExport SEXP _MuFiMeshGP_vecMulMat_cpp(SEXP vSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(vecMulMat_cpp(v, M));
    return rcpp_result_gen;
END_RCPP
}
// sliced_matMulVec_cpp
arma::cube sliced_matMulVec_cpp(arma::cube M, arma::vec v);
RcppExport SEXP _MuFiMeshGP_sliced_matMulVec_cpp(SEXP MSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(sliced_matMulVec_cpp(M, v));
    return rcpp_result_gen;
END_RCPP
}
// sliced_vecMulMat_cpp
arma::cube sliced_vecMulMat_cpp(arma::cube v, arma::mat M);
RcppExport SEXP _MuFiMeshGP_sliced_vecMulMat_cpp(SEXP vSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type v(vSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(sliced_vecMulMat_cpp(v, M));
    return rcpp_result_gen;
END_RCPP
}
// mulMat_cpp
arma::mat mulMat_cpp(arma::mat M1, arma::mat M2);
RcppExport SEXP _MuFiMeshGP_mulMat_cpp(SEXP M1SEXP, SEXP M2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M2(M2SEXP);
    rcpp_result_gen = Rcpp::wrap(mulMat_cpp(M1, M2));
    return rcpp_result_gen;
END_RCPP
}
// sliced_mulMat_cpp
arma::cube sliced_mulMat_cpp(arma::cube D, arma::mat M);
RcppExport SEXP _MuFiMeshGP_sliced_mulMat_cpp(SEXP DSEXP, SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(sliced_mulMat_cpp(D, M));
    return rcpp_result_gen;
END_RCPP
}
// hadam_vec_cpp
arma::vec hadam_vec_cpp(arma::vec v1, arma::vec v2);
RcppExport SEXP _MuFiMeshGP_hadam_vec_cpp(SEXP v1SEXP, SEXP v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type v2(v2SEXP);
    rcpp_result_gen = Rcpp::wrap(hadam_vec_cpp(v1, v2));
    return rcpp_result_gen;
END_RCPP
}
// hadam_mat_cpp
arma::mat hadam_mat_cpp(arma::mat M1, arma::mat M2);
RcppExport SEXP _MuFiMeshGP_hadam_mat_cpp(SEXP M1SEXP, SEXP M2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type M1(M1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M2(M2SEXP);
    rcpp_result_gen = Rcpp::wrap(hadam_mat_cpp(M1, M2));
    return rcpp_result_gen;
END_RCPP
}
// dx_kn_gauss_cpp
arma::mat dx_kn_gauss_cpp(arma::mat X, arma::vec x, arma::vec k1n, arma::vec k2n, arma::vec phi1sq, arma::vec phi2sq);
RcppExport SEXP _MuFiMeshGP_dx_kn_gauss_cpp(SEXP XSEXP, SEXP xSEXP, SEXP k1nSEXP, SEXP k2nSEXP, SEXP phi1sqSEXP, SEXP phi2sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type k1n(k1nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type k2n(k2nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi1sq(phi1sqSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi2sq(phi2sqSEXP);
    rcpp_result_gen = Rcpp::wrap(dx_kn_gauss_cpp(X, x, k1n, k2n, phi1sq, phi2sq));
    return rcpp_result_gen;
END_RCPP
}
// dt_kn_cpp
arma::vec dt_kn_cpp(arma::vec t1, double t2, arma::vec k2n, double H, double l);
RcppExport SEXP _MuFiMeshGP_dt_kn_cpp(SEXP t1SEXP, SEXP t2SEXP, SEXP k2nSEXP, SEXP HSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type t2(t2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type k2n(k2nSEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(dt_kn_cpp(t1, t2, k2n, H, l));
    return rcpp_result_gen;
END_RCPP
}
// dt_k_cpp
double dt_k_cpp(double t, double sigma2sq, double l);
RcppExport SEXP _MuFiMeshGP_dt_k_cpp(SEXP tSEXP, SEXP sigma2sqSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2sq(sigma2sqSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(dt_k_cpp(t, sigma2sq, l));
    return rcpp_result_gen;
END_RCPP
}
// Wijs1_gauss_cpp
arma::mat Wijs1_gauss_cpp(arma::mat x, arma::vec phi1sq, double sigma1sq);
RcppExport SEXP _MuFiMeshGP_Wijs1_gauss_cpp(SEXP xSEXP, SEXP phi1sqSEXP, SEXP sigma1sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi1sq(phi1sqSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1sq(sigma1sqSEXP);
    rcpp_result_gen = Rcpp::wrap(Wijs1_gauss_cpp(x, phi1sq, sigma1sq));
    return rcpp_result_gen;
END_RCPP
}
// Wijs2_gauss_cpp
arma::mat Wijs2_gauss_cpp(arma::mat x1, arma::mat x2, arma::vec phi1sq, double sigma1sq);
RcppExport SEXP _MuFiMeshGP_Wijs2_gauss_cpp(SEXP x1SEXP, SEXP x2SEXP, SEXP phi1sqSEXP, SEXP sigma1sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi1sq(phi1sqSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1sq(sigma1sqSEXP);
    rcpp_result_gen = Rcpp::wrap(Wijs2_gauss_cpp(x1, x2, phi1sq, sigma1sq));
    return rcpp_result_gen;
END_RCPP
}
// dx_wn_gauss_cpp
arma::mat dx_wn_gauss_cpp(arma::mat x1, arma::vec x2, arma::vec wn, arma::vec phi1sq, double sigma1sq);
RcppExport SEXP _MuFiMeshGP_dx_wn_gauss_cpp(SEXP x1SEXP, SEXP x2SEXP, SEXP wnSEXP, SEXP phi1sqSEXP, SEXP sigma1sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type wn(wnSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi1sq(phi1sqSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1sq(sigma1sqSEXP);
    rcpp_result_gen = Rcpp::wrap(dx_wn_gauss_cpp(x1, x2, wn, phi1sq, sigma1sq));
    return rcpp_result_gen;
END_RCPP
}
// dx_w_gauss_cpp
arma::vec dx_w_gauss_cpp(arma::mat x, arma::vec phi1sq, double sigma1sq);
RcppExport SEXP _MuFiMeshGP_dx_w_gauss_cpp(SEXP xSEXP, SEXP phi1sqSEXP, SEXP sigma1sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phi1sq(phi1sqSEXP);
    Rcpp::traits::input_parameter< double >::type sigma1sq(sigma1sqSEXP);
    rcpp_result_gen = Rcpp::wrap(dx_w_gauss_cpp(x, phi1sq, sigma1sq));
    return rcpp_result_gen;
END_RCPP
}
// sigmasq_cpp
double sigmasq_cpp(arma::mat Ki, arma::vec kn, double k);
RcppExport SEXP _MuFiMeshGP_sigmasq_cpp(SEXP KiSEXP, SEXP knSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Ki(KiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type kn(knSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(sigmasq_cpp(Ki, kn, k));
    return rcpp_result_gen;
END_RCPP
}
// dx_sigmasq_cpp
arma::vec dx_sigmasq_cpp(arma::mat dx_kn, arma::mat Ki, arma::vec kn);
RcppExport SEXP _MuFiMeshGP_dx_sigmasq_cpp(SEXP dx_knSEXP, SEXP KiSEXP, SEXP knSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type dx_kn(dx_knSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ki(KiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type kn(knSEXP);
    rcpp_result_gen = Rcpp::wrap(dx_sigmasq_cpp(dx_kn, Ki, kn));
    return rcpp_result_gen;
END_RCPP
}
// dt_sigmasq_cpp
double dt_sigmasq_cpp(arma::vec dt_kn, arma::mat Ki, arma::vec kn, double dt_k);
RcppExport SEXP _MuFiMeshGP_dt_sigmasq_cpp(SEXP dt_knSEXP, SEXP KiSEXP, SEXP knSEXP, SEXP dt_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type dt_kn(dt_knSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ki(KiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type kn(knSEXP);
    Rcpp::traits::input_parameter< double >::type dt_k(dt_kSEXP);
    rcpp_result_gen = Rcpp::wrap(dt_sigmasq_cpp(dt_kn, Ki, kn, dt_k));
    return rcpp_result_gen;
END_RCPP
}
// dx_a_cpp
arma::mat dx_a_cpp(arma::mat dx_kn, arma::mat Ki, arma::vec kn, double sigmasq, arma::vec dx_sigmasq);
RcppExport SEXP _MuFiMeshGP_dx_a_cpp(SEXP dx_knSEXP, SEXP KiSEXP, SEXP knSEXP, SEXP sigmasqSEXP, SEXP dx_sigmasqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type dx_kn(dx_knSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ki(KiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type kn(knSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq(sigmasqSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dx_sigmasq(dx_sigmasqSEXP);
    rcpp_result_gen = Rcpp::wrap(dx_a_cpp(dx_kn, Ki, kn, sigmasq, dx_sigmasq));
    return rcpp_result_gen;
END_RCPP
}
// dt_a_cpp
arma::vec dt_a_cpp(arma::vec dt_kn, arma::mat Ki, arma::vec kn, double sigmasq, double dt_sigmasq);
RcppExport SEXP _MuFiMeshGP_dt_a_cpp(SEXP dt_knSEXP, SEXP KiSEXP, SEXP knSEXP, SEXP sigmasqSEXP, SEXP dt_sigmasqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type dt_kn(dt_knSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ki(KiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type kn(knSEXP);
    Rcpp::traits::input_parameter< double >::type sigmasq(sigmasqSEXP);
    Rcpp::traits::input_parameter< double >::type dt_sigmasq(dt_sigmasqSEXP);
    rcpp_result_gen = Rcpp::wrap(dt_a_cpp(dt_kn, Ki, kn, sigmasq, dt_sigmasq));
    return rcpp_result_gen;
END_RCPP
}
// anisoCrossprod_cpp
arma::mat anisoCrossprod_cpp(arma::cube D, arma::vec phisq);
RcppExport SEXP _MuFiMeshGP_anisoCrossprod_cpp(SEXP DSEXP, SEXP phisqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phisq(phisqSEXP);
    rcpp_result_gen = Rcpp::wrap(anisoCrossprod_cpp(D, phisq));
    return rcpp_result_gen;
END_RCPP
}
// anisoCrossprod2_cpp
arma::cube anisoCrossprod2_cpp(arma::cube D, arma::vec phisq);
RcppExport SEXP _MuFiMeshGP_anisoCrossprod2_cpp(SEXP DSEXP, SEXP phisqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type phisq(phisqSEXP);
    rcpp_result_gen = Rcpp::wrap(anisoCrossprod2_cpp(D, phisq));
    return rcpp_result_gen;
END_RCPP
}
// anisoDist1_cpp
arma::cube anisoDist1_cpp(arma::mat x);
RcppExport SEXP _MuFiMeshGP_anisoDist1_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(anisoDist1_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// isoDist1_cpp
arma::mat isoDist1_cpp(arma::mat x);
RcppExport SEXP _MuFiMeshGP_isoDist1_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(isoDist1_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// anisoDist2_cpp
arma::cube anisoDist2_cpp(arma::mat x1, arma::mat x2);
RcppExport SEXP _MuFiMeshGP_anisoDist2_cpp(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(anisoDist2_cpp(x1, x2));
    return rcpp_result_gen;
END_RCPP
}
// isoDist2_cpp
arma::mat isoDist2_cpp(arma::mat x1, arma::mat x2);
RcppExport SEXP _MuFiMeshGP_isoDist2_cpp(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(isoDist2_cpp(x1, x2));
    return rcpp_result_gen;
END_RCPP
}
// fast_diag_cpp
NumericVector fast_diag_cpp(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _MuFiMeshGP_fast_diag_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_diag_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// fast_trace_cpp
double fast_trace_cpp(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _MuFiMeshGP_fast_trace_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_trace_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// minMat1_cpp
NumericMatrix minMat1_cpp(NumericVector x);
RcppExport SEXP _MuFiMeshGP_minMat1_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(minMat1_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// minMat2_cpp
NumericMatrix minMat2_cpp(NumericVector x1, NumericVector x2);
RcppExport SEXP _MuFiMeshGP_minMat2_cpp(SEXP x1SEXP, SEXP x2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    rcpp_result_gen = Rcpp::wrap(minMat2_cpp(x1, x2));
    return rcpp_result_gen;
END_RCPP
}
// FBMmat1_cpp
NumericMatrix FBMmat1_cpp(NumericVector x, double H, double l);
RcppExport SEXP _MuFiMeshGP_FBMmat1_cpp(SEXP xSEXP, SEXP HSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(FBMmat1_cpp(x, H, l));
    return rcpp_result_gen;
END_RCPP
}
// FBMmat2_cpp
NumericMatrix FBMmat2_cpp(NumericVector x1, NumericVector x2, double H, double l);
RcppExport SEXP _MuFiMeshGP_FBMmat2_cpp(SEXP x1SEXP, SEXP x2SEXP, SEXP HSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(FBMmat2_cpp(x1, x2, H, l));
    return rcpp_result_gen;
END_RCPP
}
// dK_H_cpp
NumericMatrix dK_H_cpp(NumericVector x, double H, double l);
RcppExport SEXP _MuFiMeshGP_dK_H_cpp(SEXP xSEXP, SEXP HSEXP, SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(dK_H_cpp(x, H, l));
    return rcpp_result_gen;
END_RCPP
}
// find_corres
IntegerVector find_corres(NumericMatrix X0, NumericMatrix X);
RcppExport SEXP _MuFiMeshGP_find_corres(SEXP X0SEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X0(X0SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(find_corres(X0, X));
    return rcpp_result_gen;
END_RCPP
}
// c2_gauss_cpp
double c2_gauss_cpp(double x, double t, double w);
RcppExport SEXP _MuFiMeshGP_c2_gauss_cpp(SEXP xSEXP, SEXP tSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(c2_gauss_cpp(x, t, w));
    return rcpp_result_gen;
END_RCPP
}
// c1_gauss_cpp
NumericVector c1_gauss_cpp(NumericVector X, double x, double sigma, NumericVector W);
RcppExport SEXP _MuFiMeshGP_c1_gauss_cpp(SEXP XSEXP, SEXP xSEXP, SEXP sigmaSEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(c1_gauss_cpp(X, x, sigma, W));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MuFiMeshGP_crossprod_cpp", (DL_FUNC) &_MuFiMeshGP_crossprod_cpp, 2},
    {"_MuFiMeshGP_matMulVec_cpp", (DL_FUNC) &_MuFiMeshGP_matMulVec_cpp, 2},
    {"_MuFiMeshGP_vecMulMat_cpp", (DL_FUNC) &_MuFiMeshGP_vecMulMat_cpp, 2},
    {"_MuFiMeshGP_sliced_matMulVec_cpp", (DL_FUNC) &_MuFiMeshGP_sliced_matMulVec_cpp, 2},
    {"_MuFiMeshGP_sliced_vecMulMat_cpp", (DL_FUNC) &_MuFiMeshGP_sliced_vecMulMat_cpp, 2},
    {"_MuFiMeshGP_mulMat_cpp", (DL_FUNC) &_MuFiMeshGP_mulMat_cpp, 2},
    {"_MuFiMeshGP_sliced_mulMat_cpp", (DL_FUNC) &_MuFiMeshGP_sliced_mulMat_cpp, 2},
    {"_MuFiMeshGP_hadam_vec_cpp", (DL_FUNC) &_MuFiMeshGP_hadam_vec_cpp, 2},
    {"_MuFiMeshGP_hadam_mat_cpp", (DL_FUNC) &_MuFiMeshGP_hadam_mat_cpp, 2},
    {"_MuFiMeshGP_dx_kn_gauss_cpp", (DL_FUNC) &_MuFiMeshGP_dx_kn_gauss_cpp, 6},
    {"_MuFiMeshGP_dt_kn_cpp", (DL_FUNC) &_MuFiMeshGP_dt_kn_cpp, 5},
    {"_MuFiMeshGP_dt_k_cpp", (DL_FUNC) &_MuFiMeshGP_dt_k_cpp, 3},
    {"_MuFiMeshGP_Wijs1_gauss_cpp", (DL_FUNC) &_MuFiMeshGP_Wijs1_gauss_cpp, 3},
    {"_MuFiMeshGP_Wijs2_gauss_cpp", (DL_FUNC) &_MuFiMeshGP_Wijs2_gauss_cpp, 4},
    {"_MuFiMeshGP_dx_wn_gauss_cpp", (DL_FUNC) &_MuFiMeshGP_dx_wn_gauss_cpp, 5},
    {"_MuFiMeshGP_dx_w_gauss_cpp", (DL_FUNC) &_MuFiMeshGP_dx_w_gauss_cpp, 3},
    {"_MuFiMeshGP_sigmasq_cpp", (DL_FUNC) &_MuFiMeshGP_sigmasq_cpp, 3},
    {"_MuFiMeshGP_dx_sigmasq_cpp", (DL_FUNC) &_MuFiMeshGP_dx_sigmasq_cpp, 3},
    {"_MuFiMeshGP_dt_sigmasq_cpp", (DL_FUNC) &_MuFiMeshGP_dt_sigmasq_cpp, 4},
    {"_MuFiMeshGP_dx_a_cpp", (DL_FUNC) &_MuFiMeshGP_dx_a_cpp, 5},
    {"_MuFiMeshGP_dt_a_cpp", (DL_FUNC) &_MuFiMeshGP_dt_a_cpp, 5},
    {"_MuFiMeshGP_anisoCrossprod_cpp", (DL_FUNC) &_MuFiMeshGP_anisoCrossprod_cpp, 2},
    {"_MuFiMeshGP_anisoCrossprod2_cpp", (DL_FUNC) &_MuFiMeshGP_anisoCrossprod2_cpp, 2},
    {"_MuFiMeshGP_anisoDist1_cpp", (DL_FUNC) &_MuFiMeshGP_anisoDist1_cpp, 1},
    {"_MuFiMeshGP_isoDist1_cpp", (DL_FUNC) &_MuFiMeshGP_isoDist1_cpp, 1},
    {"_MuFiMeshGP_anisoDist2_cpp", (DL_FUNC) &_MuFiMeshGP_anisoDist2_cpp, 2},
    {"_MuFiMeshGP_isoDist2_cpp", (DL_FUNC) &_MuFiMeshGP_isoDist2_cpp, 2},
    {"_MuFiMeshGP_fast_diag_cpp", (DL_FUNC) &_MuFiMeshGP_fast_diag_cpp, 2},
    {"_MuFiMeshGP_fast_trace_cpp", (DL_FUNC) &_MuFiMeshGP_fast_trace_cpp, 2},
    {"_MuFiMeshGP_minMat1_cpp", (DL_FUNC) &_MuFiMeshGP_minMat1_cpp, 1},
    {"_MuFiMeshGP_minMat2_cpp", (DL_FUNC) &_MuFiMeshGP_minMat2_cpp, 2},
    {"_MuFiMeshGP_FBMmat1_cpp", (DL_FUNC) &_MuFiMeshGP_FBMmat1_cpp, 3},
    {"_MuFiMeshGP_FBMmat2_cpp", (DL_FUNC) &_MuFiMeshGP_FBMmat2_cpp, 4},
    {"_MuFiMeshGP_dK_H_cpp", (DL_FUNC) &_MuFiMeshGP_dK_H_cpp, 3},
    {"_MuFiMeshGP_find_corres", (DL_FUNC) &_MuFiMeshGP_find_corres, 2},
    {"_MuFiMeshGP_c2_gauss_cpp", (DL_FUNC) &_MuFiMeshGP_c2_gauss_cpp, 3},
    {"_MuFiMeshGP_c1_gauss_cpp", (DL_FUNC) &_MuFiMeshGP_c1_gauss_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_MuFiMeshGP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
