# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprod_cpp <- function(v1, v2) {
    .Call(`_MuFiMeshGP_crossprod_cpp`, v1, v2)
}

matMulVec_cpp <- function(M, v) {
    .Call(`_MuFiMeshGP_matMulVec_cpp`, M, v)
}

vecMulMat_cpp <- function(v, M) {
    .Call(`_MuFiMeshGP_vecMulMat_cpp`, v, M)
}

sliced_matMulVec_cpp <- function(M, v) {
    .Call(`_MuFiMeshGP_sliced_matMulVec_cpp`, M, v)
}

sliced_vecMulMat_cpp <- function(v, M) {
    .Call(`_MuFiMeshGP_sliced_vecMulMat_cpp`, v, M)
}

mulMat_cpp <- function(M1, M2) {
    .Call(`_MuFiMeshGP_mulMat_cpp`, M1, M2)
}

sliced_mulMat_cpp <- function(D, M) {
    .Call(`_MuFiMeshGP_sliced_mulMat_cpp`, D, M)
}

hadam_vec_cpp <- function(v1, v2) {
    .Call(`_MuFiMeshGP_hadam_vec_cpp`, v1, v2)
}

hadam_mat_cpp <- function(M1, M2) {
    .Call(`_MuFiMeshGP_hadam_mat_cpp`, M1, M2)
}

dx_kn_gauss_cpp <- function(X, x, k1n, k2n, phi1sq, phi2sq) {
    .Call(`_MuFiMeshGP_dx_kn_gauss_cpp`, X, x, k1n, k2n, phi1sq, phi2sq)
}

dt_kn_cpp <- function(t1, t2, k2n, H, l) {
    .Call(`_MuFiMeshGP_dt_kn_cpp`, t1, t2, k2n, H, l)
}

dt_k_cpp <- function(t, sigma2sq, l) {
    .Call(`_MuFiMeshGP_dt_k_cpp`, t, sigma2sq, l)
}

Wijs1_gauss_cpp <- function(x, phi1sq, sigma1sq) {
    .Call(`_MuFiMeshGP_Wijs1_gauss_cpp`, x, phi1sq, sigma1sq)
}

Wijs2_gauss_cpp <- function(x1, x2, phi1sq, sigma1sq) {
    .Call(`_MuFiMeshGP_Wijs2_gauss_cpp`, x1, x2, phi1sq, sigma1sq)
}

dx_wn_gauss_cpp <- function(x1, x2, wn, phi1sq, sigma1sq) {
    .Call(`_MuFiMeshGP_dx_wn_gauss_cpp`, x1, x2, wn, phi1sq, sigma1sq)
}

dx_w_gauss_cpp <- function(x, phi1sq, sigma1sq) {
    .Call(`_MuFiMeshGP_dx_w_gauss_cpp`, x, phi1sq, sigma1sq)
}

sigmasq_cpp <- function(Ki, kn, k) {
    .Call(`_MuFiMeshGP_sigmasq_cpp`, Ki, kn, k)
}

dx_sigmasq_cpp <- function(dx_kn, Ki, kn) {
    .Call(`_MuFiMeshGP_dx_sigmasq_cpp`, dx_kn, Ki, kn)
}

dt_sigmasq_cpp <- function(dt_kn, Ki, kn, dt_k) {
    .Call(`_MuFiMeshGP_dt_sigmasq_cpp`, dt_kn, Ki, kn, dt_k)
}

dx_a_cpp <- function(dx_kn, Ki, kn, sigmasq, dx_sigmasq) {
    .Call(`_MuFiMeshGP_dx_a_cpp`, dx_kn, Ki, kn, sigmasq, dx_sigmasq)
}

dt_a_cpp <- function(dt_kn, Ki, kn, sigmasq, dt_sigmasq) {
    .Call(`_MuFiMeshGP_dt_a_cpp`, dt_kn, Ki, kn, sigmasq, dt_sigmasq)
}

anisoCrossprod_cpp <- function(D, phisq) {
    .Call(`_MuFiMeshGP_anisoCrossprod_cpp`, D, phisq)
}

anisoCrossprod2_cpp <- function(D, phisq) {
    .Call(`_MuFiMeshGP_anisoCrossprod2_cpp`, D, phisq)
}

anisoDist1_cpp <- function(x) {
    .Call(`_MuFiMeshGP_anisoDist1_cpp`, x)
}

isoDist1_cpp <- function(x) {
    .Call(`_MuFiMeshGP_isoDist1_cpp`, x)
}

anisoDist2_cpp <- function(x1, x2) {
    .Call(`_MuFiMeshGP_anisoDist2_cpp`, x1, x2)
}

isoDist2_cpp <- function(x1, x2) {
    .Call(`_MuFiMeshGP_isoDist2_cpp`, x1, x2)
}

fast_diag_cpp <- function(A, B) {
    .Call(`_MuFiMeshGP_fast_diag_cpp`, A, B)
}

fast_trace_cpp <- function(A, B) {
    .Call(`_MuFiMeshGP_fast_trace_cpp`, A, B)
}

minMat1_cpp <- function(x) {
    .Call(`_MuFiMeshGP_minMat1_cpp`, x)
}

minMat2_cpp <- function(x1, x2) {
    .Call(`_MuFiMeshGP_minMat2_cpp`, x1, x2)
}

FBMmat1_cpp <- function(x, H, l) {
    .Call(`_MuFiMeshGP_FBMmat1_cpp`, x, H, l)
}

FBMmat2_cpp <- function(x1, x2, H, l) {
    .Call(`_MuFiMeshGP_FBMmat2_cpp`, x1, x2, H, l)
}

dK_H_cpp <- function(x, H, l) {
    .Call(`_MuFiMeshGP_dK_H_cpp`, x, H, l)
}

find_corres <- function(X0, X) {
    .Call(`_MuFiMeshGP_find_corres`, X0, X)
}

c2_gauss_cpp <- function(x, t, w) {
    .Call(`_MuFiMeshGP_c2_gauss_cpp`, x, t, w)
}

c1_gauss_cpp <- function(X, x, sigma, W) {
    .Call(`_MuFiMeshGP_c1_gauss_cpp`, X, x, sigma, W)
}

